const LIGHTBOX_PIPELINE_ID = "7e7Bp4cnTIc"
const LIGHTBOX_PIPELINE_VERSION_ID = "W8SWXIv8ucz"
const LIGHTBOX_OUTPUT_NODE_ID = "wvYFpborOBJ"
const LIGHTBOX_INPUT_NODE_ID = "mKQpieRifcH"

const LIGHTBOX_3D_PIPELINE_ID = "46t1OZOppAv"
const LIGHTBOX_3D_PIPELINE_VERSION_ID = "IAHZCyIe58h"
const LIGHTBOX_3D_INPUT_NODE_ID = "ZXgGAl4oDCG"
const LIGHTBOX_3D_OUTPUT_MODEL_NODE_ID = "vX518jPTZ0P"
const LIGHTBOX_3D_OUTPUT_POSTER_NODE_ID = "pHlb7Ls6qc7"
const LIGHTBOX_3D_CREDIT_COST = 3

const LIGHTBOX_API_BASE_URL = "https://api.lightbox.sh/api/v1"
const LIGHTBOX_PIPELINE_RUNS_URL = `${LIGHTBOX_API_BASE_URL}/pipelines/${LIGHTBOX_PIPELINE_ID}/versions/${LIGHTBOX_PIPELINE_VERSION_ID}/runs`
const LIGHTBOX_3D_PIPELINE_RUNS_URL = `${LIGHTBOX_API_BASE_URL}/pipelines/${LIGHTBOX_3D_PIPELINE_ID}/versions/${LIGHTBOX_3D_PIPELINE_VERSION_ID}/runs`

export {
  LIGHTBOX_3D_CREDIT_COST,
  LIGHTBOX_3D_INPUT_NODE_ID,
  LIGHTBOX_3D_OUTPUT_MODEL_NODE_ID,
  LIGHTBOX_3D_OUTPUT_POSTER_NODE_ID,
  LIGHTBOX_3D_PIPELINE_ID,
  LIGHTBOX_3D_PIPELINE_RUNS_URL,
  LIGHTBOX_3D_PIPELINE_VERSION_ID,
  LIGHTBOX_API_BASE_URL,
  LIGHTBOX_INPUT_NODE_ID,
  LIGHTBOX_OUTPUT_NODE_ID,
  LIGHTBOX_PIPELINE_ID,
  LIGHTBOX_PIPELINE_RUNS_URL,
  LIGHTBOX_PIPELINE_VERSION_ID,
}
